from nltk.corpus.reader import CategorizedPlaintextCorpusReader
import re

icle = ICLECorpusReader('ICLE/spaced', r'.*\.spaced', 
	cat_pattern=r'(BGSU|CNHK|CNUK|CZKR|CZPR|CZPU|CZUN|DBAN|DNAM|DNGR|DNNI|FIAB|FIHE|FIJO|FIJY|FIOU|FITU|FRUB|FRUC|FRUL|GEAU|GEBA|GEDR|GESA|ITB|ITMC|ITMS|ITRL|ITRS|ITTO|ITVE|JPAI|JPDO|JPFJ|JPHI|JPKO|JPKW|JPKY|JPMI|JPMJ|JPMU|JPNH|JPOK|JPRI|JPSE|JPSH|JPST|JPSW|JPTF|JPTK|JPTM|JPWA|NOAC|NOAG|NOBE|NOBU|NOHB|NOHE|NOHO|NOOS|NOUO|POLU|POPZ|POSI|RUMO|SPAL|SPM|SWUG|SWUL|SWUV|TRCU|TRKE|TRME|TSKC|TSNO|TSPO|TSWI)')

icle_lemm = ICLELemmatizedCorpusReader('ICLE/spaced', r'.*\.spaced', 
	cat_pattern=r'(BGSU|CNHK|CNUK|CZKR|CZPR|CZPU|CZUN|DBAN|DNAM|DNGR|DNNI|FIAB|FIHE|FIJO|FIJY|FIOU|FITU|FRUB|FRUC|FRUL|GEAU|GEBA|GEDR|GESA|ITB|ITMC|ITMS|ITRL|ITRS|ITTO|ITVE|JPAI|JPDO|JPFJ|JPHI|JPKO|JPKW|JPKY|JPMI|JPMJ|JPMU|JPNH|JPOK|JPRI|JPSE|JPSH|JPST|JPSW|JPTF|JPTK|JPTM|JPWA|NOAC|NOAG|NOBE|NOBU|NOHB|NOHE|NOHO|NOOS|NOUO|POLU|POPZ|POSI|RUMO|SPAL|SPM|SWUG|SWUL|SWUV|TRCU|TRKE|TRME|TSKC|TSNO|TSPO|TSWI)',
	para_block_reader=read_noskipblank_block)
